# Generated by Django 4.1.7 on 2023-03-31 18:11

import app_portifolio.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=20, verbose_name='Projeto')),
                ('category', models.CharField(max_length=20, verbose_name='Descrição')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=app_portifolio.models.get_file_path, variations={'thumb': (650, 350)}, verbose_name='Imagem')),
            ],
        ),
    ]
