# Generated by Django 4.1.7 on 2023-03-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portifolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='projeto',
        ),
    ]
