# Generated by Django 4.1.7 on 2023-04-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portifolio', '0002_rename_category_project_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default=1, max_length=60, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
