# Generated by Django 4.1.7 on 2023-05-01 21:17

import app_portifolio.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portifolio', '0003_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficao', models.CharField(max_length=50, verbose_name='Profição')),
                ('duracao_ano', models.CharField(max_length=15, verbose_name='Duração')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_ano', models.CharField(max_length=15, verbose_name='Duração')),
                ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
                ('universidade', models.CharField(max_length=100, verbose_name='Universidade')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=20, verbose_name='Projeto')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_portifolio.models.get_file_path, variations={'thumb': (650, 350)}, verbose_name='Imagem')),
                ('url', models.CharField(max_length=60, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='Nome')),
                ('porcentagem', models.IntegerField(verbose_name='Porcentagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
